In [1]:
## 1. Create a single dataframe with the concatenation of all input csv files, adding a column called country

In [2]:
import pandas as pd
import os

In [3]:
print(os.getcwd())

C:\Users\croce

In [4]:
def apertura(file):
    try:
        with open(os.path.join(os.getcwd(), 'YT file', f'{file}.csv'), 'r') as f:
            for i in range(1,4):
                print(f.readline())
    except UnicodeDecodeError as e:
        print(f'\033[1m{file}: ERRORE DI ENCODING: {e}\033[0m')
    except Exception as e:
        print (f'Errore: {e}')

In [5]:
lista_file=['CAvideos', 'DEvideos', 'FRvideos', 'GBvideos', 'INvideos', 'JPvideos', 'KRvideos', 'MXvideos', 'RUvideos', 'USvideos']

In [6]:
for i in lista_file:
    apertura(i)

video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description

n1WpP7iowLc,17.14.11,"Eminem - Walk On Water (Audio) ft. BeyoncÃ©","EminemVEVO",10,2017-11-10T17:00:03.000Z,"Eminem"|"Walk"|"On"|"Water"|"Aftermath/Shady/Interscope"|"Rap",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,"Eminem's new track Walk on Water ft. BeyoncÃ© is available everywhere: http://shady.sr/WOWEminem \nPlaylist Best of Eminem: https://goo.gl/AquNpo\nSubscribe for more: https://goo.gl/DxCrDV\n\nFor more visit: \nhttp://eminem.com\nhttp://facebook.com/eminem\nhttp://twitter.com/eminem\nhttp://instagram.com/eminem\nhttp://eminem.tumblr.com\nhttp://shadyrecords.com\nhttp://facebook.com/shadyrecords\nhttp://twitter.com/shadyrecords\nhttp://instagram.com/shadyrecords\nhttp://trustshady.tumblr.com\n\nMusic video by Eminem performing Walk On Water. (C) 2017 Aftermath Records\nhttp://vevo.ly/gA7xKt"

0dBIkQ4Mz1M,17.14.11,"PLUSH - Bad Unboxing Fan Mail","iDubbbzTV",23,2017-11-13T17:00:00.000Z,"plush"|"bad unboxing"|"unboxing"|"fan mail"|"idubbbztv"|"idubbbztv2"|"things"|"best"|"packages"|"plushies"|"chontent chop",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,"STill got a lot of packages. Probably will last for another year. On a side note, more 2nd channel vids soon. editing with premiere from now on, gon' be a tedious transition, but i think it's for the best. \n\n__\n\nSUBSCRIBE â–º http://www.youtube.com/subscription_center?add_user=iDubbbztv\n\nMain Channel â–º https://www.youtube.com/user/iDubbbzTV\nSecond Channel â–º https://www.youtube.com/channel/UC-tsNNJ3yIW98MtPH6PWFAQ\nGaming Channel â–º https://www.youtube.com/channel/UCVhfFXNY0z3-mbrTh1OYRXA\n\nWebsite â–º http://www.idubbbz.com/\n\nInstagram â–º https://instagram.com/idubbbz/\nTwitter â–º https://twitter.com/Idubbbz\nFacebook â–º http://www.facebook.com/IDubbbz\nTwitch â–º http://www.twitch.tv/idubbbz\n_"

video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description

LgVi6y5QIjM,17.14.11,"Sing zu Ende! | Gesangseinlagen vom Feinsten | inscope21","inscope21",24,2017-11-13T17:08:49.000Z,"inscope21"|"sing zu ende"|"gesangseinlagen"|"gesang"|"gesungen"|"songs nachsingen"|"nachsingen"|"songs covern"|"carpool karaoke"|"witziger gesang"|"rap"|"rap cover"|"rap zu ende"|"raps nachstellen"|"nachrappen"|"nach rappen",252786,35885,230,1539,https://i.ytimg.com/vi/LgVi6y5QIjM/default.jpg,False,False,False,"Heute gibt es mal wieder ein neues Format... wenn euch das Ganze gefÃ¤llt lasst 1,5 Daumen nach oben da, dann bringen wir es nie wieder. Es wird gerappt gesungen und nichts gewusst, optimales Setup also. Kommentiert welche Songs ihr nÃ¤chstes Mal dabei haben wollt.\n\nâ–ºMerch!: https://www.inscope21.com/\n\nzu den Jungs: \n\nSascha: https://www.youtube.com/user/unsympathischtv\nShpendi: https://www.youtube.com/channel/UCm32Mjdv3OhNrDT-RXExViA\nPeter: https://www.youtube.com/channel/UCvZxLLwvrXrRf1mENhqJKkw\n\n( Die mit * gekennzeichneten Links sind Partner oder Sponsoren von mir - sprich Ã¼ber diese Links werden Einnahmen generiert)"

Bayt7uQith4,17.14.11,"Kinder ferngesteuert im Kiosk! Erwachsene abzocken - LUKE! Die Woche und ich | SAT.1","LUKE! Die Woche und ich",23,2017-11-12T22:30:01.000Z,"Kinder"|"ferngesteuert"|"Kinder ferngesteuert"|"luke mockridge kinder"|"luke die woche und ich kinder"|"Prank"|"verarschen"|"Kiosk"|"FunkgerÃ¤t"|"Falschgeld"|"VerkÃ¤ufer"|"Luke Mockridge"|"Luke Die Woche und ich"|"versteckte Kamera"|"Show"|"Sat.1"|"LDWUI"|"Comedy"|"KioskverkÃ¤ufer"|"kinder prank"|"luke robin"|"Erwachsene abzocken"|"kunden verarschen"|"kunden prank"|"kasse prank"|"versteckte Kamera luke"|"luke kinder",797196,53576,302,1278,https://i.ytimg.com/vi/Bayt7uQith4/default.jpg,False,False,False,"Kinder ferngesteuert! Kinder lassen sich sooo leicht beeinflussen. So wie Robin, der sich von Luke als KioskverkÃ¤ufer steuern lÃ¤sst. Die Kundern sind leicht irritiert.  \n\nâ–ºAbonniert den Kanal und verpasst kein â€žLUKE â€“ Die Woche und ichâ€œ-Video!\nhttps://www.youtube.com/channel/UCC2I-hHgLHQ4dTAaOhErRRQ?sub_confirmation=1\n\nâ–º â€žLUKE â€“ Die Woche und ichâ€œ auf Facebook:\nhttps://www.facebook.com/lukeswoche/\n\nâ–º Die â€žLUKE â€“ Die Woche und ichâ€œ-Webseite\nhttps://www.sat1.de/tv/luke-die-woche-und-ich\n\nEr ist charmant, frech und vor allem eins: unglaublich witzig. Luke Mockridge mischt mit seiner eigenen Show â€žLUKE! Die Woche und ichâ€œ die deutsche Comedy-Szene ordentlich auf.\n\nImpressum:\nhttp://www.myspass.de/impressum/"

FRvideos: ERRORE DI ENCODING: 'charmap' codec can't decode byte 0x81 in position 4028: character maps to <undefined>
video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description

Jw1Y-zhQURU,17.14.11,"John Lewis Christmas Ad 2017 - #MozTheMonster","John Lewis",26,2017-11-10T07:38:29.000Z,"christmas"|"john lewis christmas"|"john lewis"|"christmas ad"|"mozthemonster"|"christmas 2017"|"christmas ad 2017"|"john lewis christmas advert"|"moz",7224515,55681,10247,9479,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,False,False,"Click here to continue the story and make your own monster:\nhttp://bit.ly/2mboXgj\n\nJoe befriends a noisy Monster under his bed but the two have so much fun together that he can't get to sleep, leaving him tired by day. For Christmas Joe receives a gift to help him finally get a good nightâ€™s sleep.\n\nShop the ad\nhttp://bit.ly/2hg04Lc\n\nThe music is Golden Slumbers performed by elbow, the original song was by The Beatles. \nFind the track:\nhttps://Elbow.lnk.to/GoldenSlumbersXS\n\nSubscribe to this channel for regular video updates\nhttp://bit.ly/2eU8MvW\n\nIf you want to hear more from John Lewis:\n\nLike John Lewis on Facebook\nhttp://www.facebook.com/johnlewisretail\n\nFollow John Lewis on Twitter\nhttp://twitter.com/johnlewisretail\n\nFollow John Lewis on Instagram\nhttp://instagram.com/johnlewisretail"

3s1rvMFUweQ,17.14.11,"Taylor Swift: â€¦Ready for It? (Live) - SNL","Saturday Night Live",24,2017-11-12T06:24:44.000Z,"SNL"|"Saturday Night Live"|"SNL Season 43"|"Episode 1730"|"Tiffany Haddish"|"Taylor Swift"|"Taylor Swift Ready for It"|"s43"|"s43e5"|"episode 5"|"live"|"new york"|"comedy"|"sketch"|"funny"|"hilarious"|"late night"|"host"|"music"|"guest"|"laugh"|"impersonation"|"actor"|"improv"|"musician"|"comedian"|"actress"|"If Loving You Is Wrong"|"Oprah Winfrey"|"OWN"|"Girls Trip"|"The Carmichael Show"|"Keanu"|"Reputation"|"Look What You Made Me Do"|"ready for it?",1053632,25561,2294,2757,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,False,False,"Musical guest Taylor Swift performs â€¦Ready for It? on Saturday Night Live.\n\n#SNL #SNL43\n\nGet more SNL: http://www.nbc.com/saturday-night-live\nFull Episodes: http://www.nbc.com/saturday-night-liv...\n\nLike SNL: https://www.facebook.com/snl\nFollow SNL: https://twitter.com/nbcsnl\nSNL Tumblr: http://nbcsnl.tumblr.com/\nSNL Instagram: http://instagram.com/nbcsnl \nSNL Pinterest: http://www.pinterest.com/nbcsnl/"

INvideos: ERRORE DI ENCODING: 'charmap' codec can't decode byte 0x8d in position 1802: character maps to <undefined>
JPvideos: ERRORE DI ENCODING: 'charmap' codec can't decode byte 0x81 in position 229: character maps to <undefined>
KRvideos: ERRORE DI ENCODING: 'charmap' codec can't decode byte 0x9d in position 257: character maps to <undefined>
MXvideos: ERRORE DI ENCODING: 'charmap' codec can't decode byte 0x9d in position 2169: character maps to <undefined>
RUvideos: ERRORE DI ENCODING: 'charmap' codec can't decode byte 0x81 in position 251: character maps to <undefined>
video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description

2kyS6SvSYSE,17.14.11,"WE WANT TO TALK ABOUT OUR MARRIAGE","CaseyNeistat",22,2017-11-13T17:13:01.000Z,"SHANtell martin",748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,"SHANTELL'S CHANNEL - https://www.youtube.com/shantellmartin\nCANDICE - https://www.lovebilly.com\n\nfilmed this video in 4k on this -- http://amzn.to/2sTDnRZ\nwith this lens -- http://amzn.to/2rUJOmD\nbig drone - http://tinyurl.com/h4ft3oy\nOTHER GEAR ---  http://amzn.to/2o3GLX5\nSony CAMERA http://amzn.to/2nOBmnv\nOLD CAMERA; http://amzn.to/2o2cQBT\nMAIN LENS; http://amzn.to/2od5gBJ\nBIG SONY CAMERA; http://amzn.to/2nrdJRO\nBIG Canon CAMERA; http://tinyurl.com/jn4q4vz\nBENDY TRIPOD THING; http://tinyurl.com/gw3ylz2\nYOU NEED THIS FOR THE BENDY TRIPOD; http://tinyurl.com/j8mzzua\nWIDE LENS; http://tinyurl.com/jkfcm8t\nMORE EXPENSIVE WIDE LENS; http://tinyurl.com/zrdgtou\nSMALL CAMERA; http://tinyurl.com/hrrzhor\nMICROPHONE; http://tinyurl.com/zefm4jy\nOTHER MICROPHONE; http://tinyurl.com/jxgpj86\nOLD DRONE (cheaper but still great);http://tinyurl.com/zcfmnmd\n\nfollow me; on http://instagram.com/caseyneistat\non https://www.facebook.com/cneistat\non https://twitter.com/CaseyNeistat\n\namazing intro song by https://soundcloud.com/discoteeth\n\nad disclosure.  THIS IS NOT AN AD.  not selling or promoting anything.  but samsung did produce the Shantell Video as a 'GALAXY PROJECT' which is an initiative that enables creators like Shantell and me to make projects we might otherwise not have the opportunity to make.  hope that's clear.  if not ask in the comments and i'll answer any specifics."

1ZAPwfrtAFY,17.14.11,"The Trump Presidency: Last Week Tonight with John Oliver (HBO)","LastWeekTonight",24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency"|"last week tonight donald trump"|"john oliver trump"|"donald trump",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John Oliver discusses what we've learned so far and enlists our catheter cowboy to teach Donald Trump what he hasn't.\n\nConnect with Last Week Tonight online...\n\nSubscribe to the Last Week Tonight YouTube channel for more almost news as it almost happens: www.youtube.com/user/LastWeekTonight\n\nFind Last Week Tonight on Facebook like your mom would: http://Facebook.com/LastWeekTonight\n\nFollow us on Twitter for news about jokes and jokes about news: http://Twitter.com/LastWeekTonight\n\nVisit our official site for all that other stuff at once: http://www.hbo.com/lastweektonight"

In [7]:
def apertura(file):
    try:
        with open(os.path.join(os.getcwd(), 'YT file', f'{file}.csv'), 'r', encoding='utf-8') as f:
            for i in range(1,4):
                print(f.readline())
    except UnicodeDecodeError as e:
        print(f'\033[1m{file}: ERRORE DI ENCODING: {e}\033[0m')
    except Exception as e:
        print (f'Errore: {e}')

In [8]:
for i in lista_file:
    apertura(i)

video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description

n1WpP7iowLc,17.14.11,"Eminem - Walk On Water (Audio) ft. Beyoncé","EminemVEVO",10,2017-11-10T17:00:03.000Z,"Eminem"|"Walk"|"On"|"Water"|"Aftermath/Shady/Interscope"|"Rap",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,"Eminem's new track Walk on Water ft. Beyoncé is available everywhere: http://shady.sr/WOWEminem \nPlaylist Best of Eminem: https://goo.gl/AquNpo\nSubscribe for more: https://goo.gl/DxCrDV\n\nFor more visit: \nhttp://eminem.com\nhttp://facebook.com/eminem\nhttp://twitter.com/eminem\nhttp://instagram.com/eminem\nhttp://eminem.tumblr.com\nhttp://shadyrecords.com\nhttp://facebook.com/shadyrecords\nhttp://twitter.com/shadyrecords\nhttp://instagram.com/shadyrecords\nhttp://trustshady.tumblr.com\n\nMusic video by Eminem performing Walk On Water. (C) 2017 Aftermath Records\nhttp://vevo.ly/gA7xKt"

0dBIkQ4Mz1M,17.14.11,"PLUSH - Bad Unboxing Fan Mail","iDubbbzTV",23,2017-11-13T17:00:00.000Z,"plush"|"bad unboxing"|"unboxing"|"fan mail"|"idubbbztv"|"idubbbztv2"|"things"|"best"|"packages"|"plushies"|"chontent chop",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,"STill got a lot of packages. Probably will last for another year. On a side note, more 2nd channel vids soon. editing with premiere from now on, gon' be a tedious transition, but i think it's for the best. \n\n__\n\nSUBSCRIBE ► http://www.youtube.com/subscription_center?add_user=iDubbbztv\n\nMain Channel ► https://www.youtube.com/user/iDubbbzTV\nSecond Channel ► https://www.youtube.com/channel/UC-tsNNJ3yIW98MtPH6PWFAQ\nGaming Channel ► https://www.youtube.com/channel/UCVhfFXNY0z3-mbrTh1OYRXA\n\nWebsite ► http://www.idubbbz.com/\n\nInstagram ► https://instagram.com/idubbbz/\nTwitter ► https://twitter.com/Idubbbz\nFacebook ► http://www.facebook.com/IDubbbz\nTwitch ► http://www.twitch.tv/idubbbz\n_"

video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description

LgVi6y5QIjM,17.14.11,"Sing zu Ende! | Gesangseinlagen vom Feinsten | inscope21","inscope21",24,2017-11-13T17:08:49.000Z,"inscope21"|"sing zu ende"|"gesangseinlagen"|"gesang"|"gesungen"|"songs nachsingen"|"nachsingen"|"songs covern"|"carpool karaoke"|"witziger gesang"|"rap"|"rap cover"|"rap zu ende"|"raps nachstellen"|"nachrappen"|"nach rappen",252786,35885,230,1539,https://i.ytimg.com/vi/LgVi6y5QIjM/default.jpg,False,False,False,"Heute gibt es mal wieder ein neues Format... wenn euch das Ganze gefällt lasst 1,5 Daumen nach oben da, dann bringen wir es nie wieder. Es wird gerappt gesungen und nichts gewusst, optimales Setup also. Kommentiert welche Songs ihr nächstes Mal dabei haben wollt.\n\n►Merch!: https://www.inscope21.com/\n\nzu den Jungs: \n\nSascha: https://www.youtube.com/user/unsympathischtv\nShpendi: https://www.youtube.com/channel/UCm32Mjdv3OhNrDT-RXExViA\nPeter: https://www.youtube.com/channel/UCvZxLLwvrXrRf1mENhqJKkw\n\n( Die mit * gekennzeichneten Links sind Partner oder Sponsoren von mir - sprich über diese Links werden Einnahmen generiert)"

Bayt7uQith4,17.14.11,"Kinder ferngesteuert im Kiosk! Erwachsene abzocken - LUKE! Die Woche und ich | SAT.1","LUKE! Die Woche und ich",23,2017-11-12T22:30:01.000Z,"Kinder"|"ferngesteuert"|"Kinder ferngesteuert"|"luke mockridge kinder"|"luke die woche und ich kinder"|"Prank"|"verarschen"|"Kiosk"|"Funkgerät"|"Falschgeld"|"Verkäufer"|"Luke Mockridge"|"Luke Die Woche und ich"|"versteckte Kamera"|"Show"|"Sat.1"|"LDWUI"|"Comedy"|"Kioskverkäufer"|"kinder prank"|"luke robin"|"Erwachsene abzocken"|"kunden verarschen"|"kunden prank"|"kasse prank"|"versteckte Kamera luke"|"luke kinder",797196,53576,302,1278,https://i.ytimg.com/vi/Bayt7uQith4/default.jpg,False,False,False,"Kinder ferngesteuert! Kinder lassen sich sooo leicht beeinflussen. So wie Robin, der sich von Luke als Kioskverkäufer steuern lässt. Die Kundern sind leicht irritiert.  \n\n►Abonniert den Kanal und verpasst kein „LUKE – Die Woche und ich“-Video!\nhttps://www.youtube.com/channel/UCC2I-hHgLHQ4dTAaOhErRRQ?sub_confirmation=1\n\n► „LUKE – Die Woche und ich“ auf Facebook:\nhttps://www.facebook.com/lukeswoche/\n\n► Die „LUKE – Die Woche und ich“-Webseite\nhttps://www.sat1.de/tv/luke-die-woche-und-ich\n\nEr ist charmant, frech und vor allem eins: unglaublich witzig. Luke Mockridge mischt mit seiner eigenen Show „LUKE! Die Woche und ich“ die deutsche Comedy-Szene ordentlich auf.\n\nImpressum:\nhttp://www.myspass.de/impressum/"

video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description

Ro6eob0LrCY,17.14.11,Malika LePen : Femme de Gauche - Trailer,Le Raptor Dissident,24,2017-11-13T17:32:55.000Z,"Raptor""|""Dissident""|""Expliquez""|""moi""|""cette""|""merde",212702,29282,1108,3817,https://i.ytimg.com/vi/Ro6eob0LrCY/default.jpg,False,False,False,"Dimanche.\n18h30.\nSoyez présents pour la vidéo la plus réalistiquement haineuse du YouTube Game.\n\nStrike sous 24h garanti.\n\nMontage de NastyTanooki : https://www.youtube.com/channel/UCJvYnKvJZSIz-2deI7Xppww\n\n------------------------------------------------------------------------------------------------\n\nRAPTORCOACHING PRO : raptorcoachingpro@gmail.com\n\nSi tu pratiques la musculation et que tu es intéressé(e) par un Programme/Diète Personnalisés + Suivi, envoie nous un mail avec ton Nom/Âge/Objectif et le coach s'occupera de toi. Le training sera réalisé en fonction des objectifs aussi bien muscu prise de muscle/sèche que prépa sportive/concours.\n\nPROZIS : -10% sur tout le site http://prozis.com/lb5 avec le coupon COACHINGPRO10\n\n------------------------------------------------------------------------------------------------\n\nRejoins la dissidence jurassique sur les réseaux sociaux :\n\nFACEBOOK : https://www.facebook.com/LeRaptorDissident\n\nTWITTER : https://twitter.com/RaptorDissident\n\nSNAPCHAT : raptorvswild\n\nINSTAGRAM : raptorvsfonte\n\nTIPEE D'OR : https://www.tipeee.com/le-raptor-dissident\n\n------------------------------------------------------------------------------------------------\n\nSources :\n\nMusique : https://www.youtube.com/watch?v=7vn5BD0oadM\n\nMa Bannière et mon Avatar YouTube : LeDessinator https://www.youtube.com/channel/UCXLIl-l_zi1lCVrJHLJqJew"

Yo84eqYwP98,17.14.11,"LA PIRE PARTIE ft Le Rire Jaune, Pierre Croce, Fabien Olicard, Nad Rich' Hard, Max Bird, Studio Vrac",Le Labo,24,2017-11-12T15:00:02.000Z,[none],432721,14053,576,1161,https://i.ytimg.com/vi/Yo84eqYwP98/default.jpg,False,False,False,"Le jeu de société: https://goo.gl/hhG1Ta\n\nGagner le jeu signé par tous les joueurs: \n\nChaîne de Studio Vrac: https://goo.gl/HVPoJs\nChaîne du Rire Jaune: https://goo.gl/JqUGNj\nChaîne de Fabien Olicard: https://goo.gl/uc6zii\nChaîne de Nad Rich' Hard: https://goo.gl/hiy2mw\nChaîne de Pierre Croce: https://goo.gl/PVijXG\nChaîne de Max Bird: https://goo.gl/A9Zc1r\nChaîne des astuces de Margaux: https://goo.gl/Pz9L1v\n\n\n------------------\n\nSi tu m'envoies un colis ou une lettre, n'oublie pas d'y laisser ton adresse pour t'ajouter à la carte des abonnés !\n\nLa carte des abonnés: https://goo.gl/438YIX\n\n\nMa liste de recherches de cartes Battle Tube : https://goo.gl/zG6Npz\nMa liste de recherches de cartes Yu-Gi-Oh : https://goo.gl/40bUBO\nMa liste de recherches de jeux GameCube : https://goo.gl/cMEAM7\n\n------------------\n\nTu veux m'envoyer un colis ?\nC'est ici:\n\nDoc Seven\nUne pièce en plus\n119 Avenue Paul Vaillant Couturier\n94250 Gentilly\n\n------------------\n\nTu veux m'envoyer une lettre ?\nC'est ici:\n\nDoc Seven\n8, rue du Fg Poissonnière\n75010 Paris\n\n------------------\n\nSi vous venez de ma chaîne principale, vous me connaissez, sinon allez faire un tour sur ma chaîne principale: \nhttps://www.youtube.com/channel/UC5Twj1Axp_-9HLsZ5o_cEQQ\n\nN'oubliez pas de vous abonner et n'hésitez pas à me suivre sur les réseaux sociaux!\n\nFacebook: https://www.facebook.com/DocSevenTV\nTwitter: https://twitter.com/DocSevenTV\nInstagram: https://www.instagram.com/docseventv/\n\n------------------\n\nCrédit(s) musique:\nArtistes récurrents:\n- KronoMuzik : https://www.youtube.com/channel/UC5C9...\n\n- Anthox : https://www.youtube.com/user/wildesyde\n\n- Efisio Cross : https://www.youtube.com/user/EfisioSymphony\n\nGraphisme de la chaîne:\nBoidin: https://www.youtube.com/user/battlefrite"

video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description

Jw1Y-zhQURU,17.14.11,"John Lewis Christmas Ad 2017 - #MozTheMonster","John Lewis",26,2017-11-10T07:38:29.000Z,"christmas"|"john lewis christmas"|"john lewis"|"christmas ad"|"mozthemonster"|"christmas 2017"|"christmas ad 2017"|"john lewis christmas advert"|"moz",7224515,55681,10247,9479,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,False,False,"Click here to continue the story and make your own monster:\nhttp://bit.ly/2mboXgj\n\nJoe befriends a noisy Monster under his bed but the two have so much fun together that he can't get to sleep, leaving him tired by day. For Christmas Joe receives a gift to help him finally get a good night’s sleep.\n\nShop the ad\nhttp://bit.ly/2hg04Lc\n\nThe music is Golden Slumbers performed by elbow, the original song was by The Beatles. \nFind the track:\nhttps://Elbow.lnk.to/GoldenSlumbersXS\n\nSubscribe to this channel for regular video updates\nhttp://bit.ly/2eU8MvW\n\nIf you want to hear more from John Lewis:\n\nLike John Lewis on Facebook\nhttp://www.facebook.com/johnlewisretail\n\nFollow John Lewis on Twitter\nhttp://twitter.com/johnlewisretail\n\nFollow John Lewis on Instagram\nhttp://instagram.com/johnlewisretail"

3s1rvMFUweQ,17.14.11,"Taylor Swift: …Ready for It? (Live) - SNL","Saturday Night Live",24,2017-11-12T06:24:44.000Z,"SNL"|"Saturday Night Live"|"SNL Season 43"|"Episode 1730"|"Tiffany Haddish"|"Taylor Swift"|"Taylor Swift Ready for It"|"s43"|"s43e5"|"episode 5"|"live"|"new york"|"comedy"|"sketch"|"funny"|"hilarious"|"late night"|"host"|"music"|"guest"|"laugh"|"impersonation"|"actor"|"improv"|"musician"|"comedian"|"actress"|"If Loving You Is Wrong"|"Oprah Winfrey"|"OWN"|"Girls Trip"|"The Carmichael Show"|"Keanu"|"Reputation"|"Look What You Made Me Do"|"ready for it?",1053632,25561,2294,2757,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,False,False,"Musical guest Taylor Swift performs …Ready for It? on Saturday Night Live.\n\n#SNL #SNL43\n\nGet more SNL: http://www.nbc.com/saturday-night-live\nFull Episodes: http://www.nbc.com/saturday-night-liv...\n\nLike SNL: https://www.facebook.com/snl\nFollow SNL: https://twitter.com/nbcsnl\nSNL Tumblr: http://nbcsnl.tumblr.com/\nSNL Instagram: http://instagram.com/nbcsnl \nSNL Pinterest: http://www.pinterest.com/nbcsnl/"

video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description

kzwfHumJyYc,17.14.11,Sharry Mann: Cute Munda ( Song Teaser) | Parmish Verma | Releasing on 17 November,Lokdhun Punjabi,1,2017-11-12T12:20:39.000Z,"sharry mann|""sharry mann new song""|""sharry mann cute munda""|""sharry mann latest song""|""sharry mann punjabi song 2017""|""parmish verma""|""parmish verma new song""|""parmish verma sharry mann""|""parmish verma sharry mann new song""|""parmish verma cute munda""|""new punjabi song 2017""|""punjabi song 2017""|""parmish verma new song 2017""|""parmish verma latest song 2017""|""punjabi songs 2017""",1096327,33966,798,882,https://i.ytimg.com/vi/kzwfHumJyYc/default.jpg,FALSE,FALSE,FALSE,"Presenting Sharry Mann latest Punjabi Song  Cute Munda Teaser . The music of new punjabi song is given by Gift Rulers while lyrics are penned by Zaildar Pargat Singh. The video is directed by Parmish Verma. \nEnjoy and stay connected with us!! \n\nSong : Cute Munda\nSinger : Sharry Mann\nStarring : Sharry Mann, Rumman & Parmish Verma\nMusic : Gift Rulers\nLyrics : Zaildar Pargat Singh\nConcept, Screenplay & Direction : Parmish Verma\nOnline Promotions : Gold Media\nCopyright: Lokdhun\n\nFull Song Releasing on 17th November\n\n\nFor more new Punjabi songs, latest Punjabi videos, funny Punjabi comedy scenes and new Punjabi movies, subscribe our channel - http://goo.gl/NnoXVB\n\n\nLike us on Facebook - https://www.facebook.com/LokdhunPunjabiOfficial/\nFollow us on Twitter - https://twitter.com/lokdhunpunjabi\nFollow us on Instagram - https://www.instagram.com/lokdhunpunjabi\nVisit us on https://www.lokdhun.com"

zUZ1z7FwLc8,17.14.11,"पीरियड्स के समय, पेट पर पति करता ऐसा, देखकर दंग रह जायेंगे",HJ NEWS,25,2017-11-13T05:43:56.000Z,"पीरियड्स के समय|""पेट पर पति करता ऐसा""|""देखकर दंग रह जायेंगे""|""latest news""|""today news""|""news""|""breaking news""|""current news""|""world news""|""hj news updates""|""bollywood updates""|""news channel in hindi""|""entertainment news""|""merrage""|""love""|""break up""|""perideus time""|""pragenent girl""|""baby born""",590101,735,904,0,https://i.ytimg.com/vi/zUZ1z7FwLc8/default.jpg,TRUE,FALSE,FALSE,"पीरियड्स के समय, पेट पर पति करता ऐसा, देखकर दंग रह जायेंगे \n\nWatch this video :- https://youtu.be/zUZ1z7FwLc8\n\nHere is the secret of the death of PCS wife Namrata on February 16, 2017, still persisted after 9 months. In the case, the relatives of the deceased had accused the in-laws of torture against dowry, after which the police sent the accused husband and mother-in-law and sent them to jail.\n\nThe mother of the deceased Kiran said, Humility was my little daughter, she was preparing to become an IAS. Then there was a relation of dedication from a matrimonial website. We were watching the relationship for our eldest daughter, I liked the humility. \n- We did not want that little sister's marriage to be a big one before, but humility itself was refusing marriage, but Mother of Divine took it to the center. Dipartan was PCS, so we also agreed for marriage. . ''\nDeepa's mother Anuradha had said that humility could continue her studies even after marriage. On this condition she was ready for marriage, both of them were married on June 10, 2015.\n- Cajun Sister Chitra said, The sister was emotionally attached to the lamp, there were many things that she used to share with me, but Deep used to torture her for dowry.\n- During the periods, the lamp beat him on the stomach and back. Sister came home and asked me to massage the stomach and back. She used to tell that Deep struck a lot, massage it. \n- I had advised sister to take the Divorce, but she did not want to break the relationship.\n\nSubscribe Us for Latest News & Updates ► https://goo.gl/K8pjDQ\n\nStay Connected with Us :\n\nFollow Us On Facebook ► https://goo.gl/GEkOqP\n\nFollow Us On Twitter ►  https://twitter.com/hjnews4u\n\nFollow Us On Google plus ►  https://goo.gl/LZglUF\n\nHJ NEWS !!\n\nHJ NEWS outbreaks the conventional news reading and brings to you the real face of every information at one click! Latest news from India and the world, politics and nation, entertainment, sports and science. Witness the panoramic vision of the state on every aspect you can think of! \nIt is easy for every person to watch the news in form of video rather than reading every sentance..\n\nSo, Friends Please Watch , Like , Share & Subscribe HJ NEWS"

video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description

5ugKfHgsmYw,18.07.02,陸自ヘリ、垂直に落下＝路上の車が撮影,時事通信映像センター,25,2018-02-06T03:04:37.000Z,"事故|""佐賀""|""佐賀県""|""ヘリコプター""|""ヘリ""|""自衛隊""|""墜落""|""落下""|""現場""|""神埼市""|""ドライブレコーダー""",188085,591,189,0,https://i.ytimg.com/vi/5ugKfHgsmYw/default.jpg,TRUE,FALSE,FALSE,佐賀県神埼市の民家に墜落した陸上自衛隊のＡＨ６４Ｄ戦闘ヘリコプターが垂直に落下する様子を、近くにいた車のドライブレコーダーが捉えていたことが６日分かった。\n　現場の南から撮影された映像では、東から西に飛行するヘリが突然、機首を下に向けてきりもみ回転するように落下。ヘリの急降下と同時に、機体の一部とみられる物体が落ちていく様子も映っていた。\n　録画した佐賀城北自動車学校（佐賀市）によると、撮影場所は現場から約１．５キロメートル南の神埼市内の路上。時間調整のため停車していた送迎車のドライブレコーダーに、偶然映り込んでいたという。佐賀城北自動車学校提供。【時事通信映像センター】

ohObafdd34Y,18.07.02,イッテQ お祭り男宮川×手越 巨大ブランコ②,神谷えりな Kamiya Erina 2,1,2018-02-06T04:01:56.000Z,[none],90929,442,88,174,https://i.ytimg.com/vi/ohObafdd34Y/default.jpg,FALSE,FALSE,FALSE,

video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description

RxGQe4EeEpA,17.14.11,좋아 by 민서_윤종신_좋니 답가,라푸마코리아,22,2017-11-13T07:07:36.000Z,"라푸마|""윤종신""|""좋니""|""좋아""|""샬레""|""민서""",156130,1422,40,272,https://i.ytimg.com/vi/RxGQe4EeEpA/default.jpg,FALSE,FALSE,FALSE,"윤종신 '좋니'의 답가 '좋아' 최초 공개!\n그 여자의 이야기를 지금 만나보세요. \n\n좋아, 딱 잊기 좋은 추억 정도야\n난 딱 알맞게 너를 사랑했어.\n\n'좋니'의 그에게 보내는 그 여자의 답가\n애절한 이별 후에도, 설레는 사랑의 시작에도\n라푸마가 함께합니다."

hH7wVE8OlQ0,17.14.11,JSA 귀순 북한군 총격 부상,Edward,25,2017-11-13T10:59:16.000Z,"JSA|""귀순""|""북한군""|""총격""|""부상""|""JSA 귀순 북한군 총격 부상""",76533,211,28,113,https://i.ytimg.com/vi/hH7wVE8OlQ0/default.jpg,FALSE,FALSE,FALSE,"[채널A단독]北 병사 현재 '의식불명'… 혈압 떨어지는 중 \n[채널A단독]우리측 초소 50m 앞서 의식 잃고 쓰러져 \n[채널A단독]北 병사 귀순 전 이미 북측서 총성 \n[채널A단독]귀순 北 병사, 유엔 헬기로 아주대병원 이송 \n北 신문 트럼프는 늙다리, 평화 파괴자 행각 \n트럼프, 北 '늙다리' 발언에 발끈 \n트럼프 김정은 작고 뚱뚱… 왜 나를 모욕하나"

video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description

SbOwzAl9ZfQ,17.14.11,Capítulo 12 | MasterChef 2017,MasterChef 2017,24,2017-11-13T06:06:22.000Z,"MasterChef Junior 2017|""TV Azteca""|""recetas""|""cocina""|""Anette Michel""|""Betty Vázquez""|""Benito Molina""|""Adrián Herrera""|""master chef mexico""|""masterchef""|""master chef""|""master chef mexico 2017""|""masterchef mexico jueces""|""la cocina más famosa de méxico""|""reality de cocina más famoso de méxico""|""capítulo 12""|""episodio 12""|""capitulo masterchef""|""capitulo masterchef mexico 2017""|""programa masterchef de hoy""",310130,4182,361,1836,https://i.ytimg.com/vi/SbOwzAl9ZfQ/default.jpg,FALSE,FALSE,FALSE,"Disfruta la presencia del Chef Torreblanca en MasterChef, el duelo de pasteles, las mesas regionales de los chefs Benito, Betty y Herrera, la preparación de un tamal  artesanal y la salida del Padre Beto.\n\nMasterChef 2017\nVisita nuestro sitio oficial:\nhttp://www.aztecatrece.com/masterchef\n\nMasterChef regresa este 2017 más exigente que nunca. Descubre quién será el mejor cocinero de México en la cocina más famosa del mundo. Tv Azteca"

klOV6Xh-DnI,17.14.11,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUNCIA A ¨La Voz Mexico 7¨TELEVISA 11/11/2017,Micky Contreras Martinez,22,2017-11-13T05:11:58.000Z,La Voz Mexico 7,104972,271,174,369,https://i.ytimg.com/vi/klOV6Xh-DnI/default.jpg,FALSE,FALSE,FALSE,ALEXA EX-INTEGRANTE DEL GRUPO TIMBIRICHE RENUNCIA A ¨La Voz Mexico 7¨TELEVISA 11/11/2017

video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description


In [9]:
def apertura(file):
    try:
        df = pd.read_csv(os.path.join(os.getcwd(), 'YT file', f'{file}.csv'), encoding='utf-8')
        return df
    except UnicodeDecodeError as e:
        print(f'\033[1m{file}: ERRORE DI ENCODING: {e}\033[0m')
        return None
    except Exception as e:
        print (f'Errore: {e}')
        return None

In [10]:
for i in lista_file:
    apertura(i)

JPvideos: ERRORE DI ENCODING: 'utf-8' codec can't decode bytes in position 253-254: unexpected end of data
KRvideos: ERRORE DI ENCODING: 'utf-8' codec can't decode bytes in position 253-254: unexpected end of data
MXvideos: ERRORE DI ENCODING: 'utf-8' codec can't decode byte 0xc3 in position 254: unexpected end of data
RUvideos: ERRORE DI ENCODING: 'utf-8' codec can't decode byte 0xd0 in position 254: unexpected end of data

In [11]:
country_files = {
    'usa': 'USvideos',
    'ca':  'CAvideos',
    'de':  'DEvideos',
    'fr':  'FRvideos',
    'gb':  'GBvideos',
    'in':  'INvideos',
    'jp':  'JPvideos',
    'kr':  'KRvideos',
    'mx':  'MXvideos',
    'ru':  'RUvideos',
}

dfs = {}
for country, filename in country_files.items():
    df = pd.read_csv(os.path.join(os.getcwd(), 'YT file', f'{filename}.csv'),
                      encoding='utf-8', encoding_errors='replace')
    df['country'] = country
    dfs[country] = df

In [12]:
dfs.keys()

dict_keys(['usa', 'ca', 'de', 'fr', 'gb', 'in', 'jp', 'kr', 'mx', 'ru'])

In [13]:
dfs['ca'].head(2)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,ca
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,ca

In [14]:
full = pd.concat(dfs.values(), ignore_index=True)
full.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,usa
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John...",usa
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,usa
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...,usa
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,usa

In [15]:
full.columns

Index(['video_id', 'trending_date', 'title', 'channel_title', 'category_id',
       'publish_time', 'tags', 'views', 'likes', 'dislikes', 'comment_count',
       'thumbnail_link', 'comments_disabled', 'ratings_disabled',
       'video_error_or_removed', 'description', 'country'],
      dtype='object')

In [16]:
full.shape

(375942, 17)

In [17]:
full['country'].value_counts()

country
usa    40949
ca     40881
de     40840
ru     40739
fr     40724
mx     40451
gb     38916
in     37352
kr     34567
jp     20523
Name: count, dtype: int64

In [18]:
## 2. Extract all videos that have no tag.

In [19]:
full.isnull().any()

video_id                  False
trending_date             False
title                     False
channel_title             False
category_id               False
publish_time              False
tags                      False
views                     False
likes                     False
dislikes                  False
comment_count             False
thumbnail_link            False
comments_disabled         False
ratings_disabled          False
video_error_or_removed    False
description                True
country                   False
dtype: bool

In [20]:
import re

In [21]:
full['tags'].value_counts().head(10)

tags
[none]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          37698
шарий|"шарий блог"|"новое видео шарий"|"шарий новое"|"анатолий шарий"|"шарий анатолий"|"ifhbq"|"видео шария"|"толя шарий"                                                                                                                                                                                                                                                                                                                                                                                                         353
The Late Show|"Stephen Colbert"|"Colbert"|"Late Show"|"celebrities"|"late night"|"talk show"|"skits"|"bit"|"monologue"|"The Late Late Show"|"Late Late Show"|"letterman"|"david letterman"|"comedian"|"impressions"|"CBS"|"joke"|"jokes"|"funny"|"funny video"|"funny videos"|"humor"|"celebrity"|"celeb"|"hollywood"|"famous"|"James Corden"|"Corden"|"Comedy"                                                                                                                                                                   341
Vaani rani|"rani"|"Radhika in funny character"|"venu aravind"|"SunTV"|"VaniRani"|"vani"|"vaani"|"Radhika's dual role serial"|"Ranimma veetu kuripu"|"Radhika as lawyer in serial"|"radikaa"|"rathika"|"Radhika's new"                                                                                                                                                                                                                                                                                                             313
flowers tv|"uppum mulakum"|"uppum"|"biju sopanam"|"Balanchandran"|"Neelima"|"juhi rustagi"|"flower tv comedy"|"flower tv malayalam"|"balanchandran"|"entertainment"|"best comedy serial malayalam"|"s p sreekumar"|"college campus comedy"|"marimayam"|"sneha sreekumar"|"programme"|"moosa"|"m80 moosa"|"funny"|"flower tv comedy night"|"malayalam comedy"|"+uppum mulakum"                                                                                                                                                     299
etv Plus|"etv comedy show"|"3 Idiots"|"anchor ravi"|"Chinnadana Neekosam"|"express raja"|"hungama"|"Kick"|"Nandini Vs Nandini"|"Pataas"|"jabardasth"|"extra jabardasth"|"naga babu"|"roja"|"anchor anasuya"|"pove pora"|"comedy short films"|"yadamma raju"|"chalaki chanti"|"sudigali sudeer"|"anchor suma"|"comedy show"|"anchor sreemukhi"|"comedy skits in telugu"|"telugu comedy tracks"|"racha ravi"|"allare allari"|"sardaga kasepu"|"ejunction"|"anchor pradeep"|"pataas punches"|"anchor vishnupriya"|"getup srinu"      252
best vines 2018|"funny vines"|"funny videos"|"funniest videos 2018"                                                                                                                                                                                                                                                                                                                                                                                                                                                               247
James Corden|"The Late Late Show"|"Colbert"|"late night"|"late night show"|"Stephen Colbert"|"Comedy"|"monologue"|"comedian"|"impressions"|"celebrities"|"carpool"|"karaoke"|"CBS"|"Late Late Show"|"Corden"|"joke"|"jokes"|"funny"|"funny video"|"funny videos"|"humor"|"celebrity"|"celeb"|"hollywood"|"famous"                                                                                                                                                                                                                 245
etv daily serials|"etv daily soaps"|"etv fictions"|"bharyamani"|"etv chandramukhi"|"etv manasu mamata"|"swathi chinukulu"|"sikharam"|"anthapuram"|"adade aadaram"|"cash"|"jabardasth"|"extra jabardasth"|"nagababu"|"latest telugu serials"|"Krish"|"savithri"|"manasu mamatha"|"naperu meenakshi"|"gokulamlo seetha"|"antahpuram"|"seetamma vakitlo"|"champion"|"dhee jodi"                                                                                                                                                      229
Vaani rani|"rani"|"Radhika in funny character"|"venu aravind"|"SunTV"|"VaniRani"|"vani"|"vaani"|"Radhika's dual role serial"|"Ranimma veetu kuripu"|"Radhika as lawyer in serial"|"radikaa"|"Radhika's new"                                                                                                                                                                                                                                                                                                                       226
Name: count, dtype: int64

In [22]:
full['tags'].value_counts().tail(10)

tags
مسلسل أبو العروسة"|"مشاهدة حلقات أبو العروسة يوتيوب"|"أبو العروسة الحلقة 53"|"أبو العروسة الحلقة الثالثة والخمسون"|"كواليس مسلسل أبو العروسة"|"Abu El 3rosa"|"سيد رجب"|"سوسن بدر"|"ولاء الشريف"|"مدحت صالح"|"نرمين الفقي"|"رانيا فريد شوقي"|"محمد عادل"|"سابع جار"|"عائلة زيزو"|"الطوفان"|"محمد صلاح"|"dmc"|"dmc tv"|"dmc sports"|"dmc hd"|"dmc drama"|"ليفربول‎"|"ريال مدريد‎"|"تشيلسي"|"محمد رمضان"|"البيت الكبير"|"رامي عصام"|"علي ربيع"|"وليد ازارو"|"سوار شعيب"|"سعد لمجرد"|"حمزة نمرة"|"خيري رمضان                                                            1
fanfiction fairy tail Une inconue épisode 3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
trolls"|"Trolls: En Avant La Musique"|"songs that stick in french"|"Haut Les Cheveux"|"Haut Les Cœurs"|"trollstv in french"|"hair in the air                                                                                                                                                                                                                                                                                                                                                                                                                        1
NFL|"Football"|"offense"|"defense"|"afc"|"nfc"|"American Football"|"highlight"|"highlights"|"game"|"games"|"sport"|"sports"|"action"|"play"|"plays"|"season"|"2017"|"rookie"|"rookies"|"recap"|"run"|"sprint"|"catch"|"huge"|"amazing"|"touchdown"|"td"|"week 9"|"wk 9"|"new england"|"patriots"|"pats"|"denver"|"broncos"|"lewis"|"kickoff"|"kick return"|"return td"|"special teams"|"sp:dt=2017-11-12T20:30:00-05:00"|"sp:vl=en-US"|"sp:st=football"|"sp:li=nfl"|"sp:ti:home=Den"|"sp:ti:away=NE"|"sp:scp=athlete_in_match"|"sp:ty=high"|"nfl-lewdio"            1
лайфхаки|"для лета"|"летние лайфхаки"|"6 лайфхаков для лета"|"лучшие лайфхаки"|"упрощение жизни"|"хаки"|"способы"|"лайфхак"|"подборка"|"как сделать"|"сделай сам"|"своими руками"|"интересные идеи"|"топ лайфхаки"|"самоделки"|"diy"|"идеи"|"в домашних условиях"|"хитрости"|"полезные советы"|"10 лайфхаков"|"7 лайфхаков"|"творчество"|"life hacks"|"переработка"|"мандарин"|"mandarin new"|"2018"|"лайфхаки для жизни"|"бери и делай"|"хендмейд"|"life hack"|"10 лайфхаков для лета"                                                                             1
ваз 2114|"четырка"|"чепырка"|"ваз"|"лада"|"2114"|"тюнинг"|"ремонт"|"ваз2114"|"абрам"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
лизун|"лизуна"|"рецепт лизуна"|"проверяю рецепты"|"лизуна без клея"|"лизун без клея"|"лизун без"|"без клея"|"слайм"|"БЕЗ КЛЕЯ и с клеем"|"как сделать лизун"|"лизун своими руками"|"лизун в домашних условиях"|"своими руками"|"diy"|"slime"|"ЛИЗУН ИЗ ЗУБНОЙ ПАСТЫ"|"прозрачный лизун"|"crystal slime"|"как быстро сделать лизуна"|"хэндгам"|"toothpaste slime"|"как сделать лизуна за 5 минут"|"Тетрабората"|"как сделать"|"handgum"|"марффа"|"marffa"                                                                                                            1
мото|"блогер"|"скутер"|"банка"|"пиво"|"глушитель"|"прямоток"|"что"|"если"|"тюнинг"|"moto"|"scooter"|"roller"|"beer"|"can"|"instead"|"silencer"|"exhaust"                                                                                                                                                                                                                                                                                                                                                                                                            1
Дзюба|"интервью Дзюбы"|"интервью"|"Дзюба сборная"|"Дзюба критика"|"хватит гнобить сборную России"|"Россия Саудовская Аравия"|"усы надежды"|"Черчесов"|"Черчесов сборная"|"сборная"|"сборная России"|"Россия чемпионат мира"|"ЧМ2018"|"2018"|"чемпионат мира"|"WC2018"|"World Cup 2018"|"трансферы"|"трансферы Спартака"|"кого купит Спартак"|"Спартак"|"Spartak"|"ФК Спартак"|"Зенит"|"Zenit"|"ЦСКА"|"трансферы Зенита"|"матч"|"фанаты"|"Краснодар"|"рфпл"|"премьер-лига"|"ставки"|"прогноз"|"обзор"|"разбор"|"матч тв"|"Борзыкин"|"аналитика"|"фабрика футбола"    1
Россия - Саудовская Аравия|"Египет - Уругвай"|"Португалия - Испания"|"ЧМ 2018"|"россия саудовская аравия 14.06.2018 обзор"|"Уругвай - Египет 15.06.2018 обзор"|"Испания Португалия 15.06.2018 обзор"|"прогнозы на чемпионат мира 2018"|"россия"|"чемпионат мира 2018 по футболу"|"футбол"|"матч"                                                                                                                                                                                                                                                                   1
Name: count, dtype: int64

In [23]:
no_tags = full[full['tags'] == '[none]']
print(no_tags.shape)
no_tags.head(3)

(37698, 17)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
42,NZFhMSgbKKM,17.14.11,Dennis Smith Jr. and LeBron James go back and ...,Ben Rohrbach,17,2017-11-13T15:11:00.000Z,[none],945,7,5,8,https://i.ytimg.com/vi/NZFhMSgbKKM/default.jpg,False,False,False,NaN,usa
97,xfmipNU4Odc,17.14.11,Edna's registered owner thought she was dead f...,Hope For Paws - Official Rescue Channel,15,2017-11-10T18:02:04.000Z,[none],284666,16396,81,949,https://i.ytimg.com/vi/xfmipNU4Odc/default.jpg,False,False,False,Please donate $5 and help us save more lives:\...,usa
133,X7flefV8tec,17.14.11,"President Bill Clinton On Dictators, Democracy...",Team Coco,24,2017-11-09T02:37:49.000Z,[none],366180,4364,4448,1997,https://i.ytimg.com/vi/X7flefV8tec/default.jpg,False,False,False,#ConanNYC Highlight: President Clinton talks a...,usa

In [24]:
full[full['tags'].str.contains(r'\[none\]', flags = re.I)].shape

(37698, 17)

In [25]:
## 3. For each channel, determine the total number of views

In [26]:
total_views = full.groupby('channel_title', as_index= False)['views'].sum()
total_views

                channel_title    views
0                  ! 세상에 무슨일이  3942977
1               !!8時だよ面白ネタ大集合    50207
2              !BTS・TWICE まとめ     7310
3      !Los amorosos Virales¡     6069
4                     !t Live   240038
...                       ...      ...
37819              ５分でできる DIY   272607
37820                  ＢＡＳＨｔｖ   116292
37821           Ｋのフィッシングちゃんねる    37165
37822                 ＷＡＪＯＩＫＡ   424129
37823                💜Sandrea   347155

[37824 rows x 2 columns]

In [27]:
total_views.sort_values('views', ascending = False).head(10)

              channel_title        views
4564    ChildishGambinoVEVO  11016766510
15536  Marvel Entertainment  10430605449
17726            NickyJamTV   9479859505
18466                 Ozuna   8623329509
28412               ibighit   8205572221
6689              DrakeVEVO   7637228580
2788              Bad Bunny   7124207494
2101       ArianaGrandeVevo   6202230488
28621      jypentertainment   5802822913
7047             Ed Sheeran   5775405574

In [28]:
## 4. Save all rows with disabled comments and disabled ratings, or that have video_error_or_removed 
## in a new dataframe called excluded, and remove those rows from the original dataframe.

In [29]:
full['comments_disabled'].value_counts()

comments_disabled
False    367479
True       8463
Name: count, dtype: int64

In [30]:
full['ratings_disabled'].value_counts()

ratings_disabled
False    368634
True       7308
Name: count, dtype: int64

In [31]:
full['video_error_or_removed'].value_counts()

video_error_or_removed
False    375689
True        253
Name: count, dtype: int64

In [32]:
excluded = full[((full['comments_disabled']== True) & (full['ratings_disabled']== True)) | (full['video_error_or_removed'] == True)]
excluded.head(1)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
1435,Kn5UgGQukYQ,17.21.11,Breaking Bad's Bryan Cranston on Meeting Charl...,hudsonunionsociety,1,2016-10-14T21:14:51.000Z,"Breaking Bad|""Bryan Cranston""|""malcom in the m...",15058,0,0,0,https://i.ytimg.com/vi/Kn5UgGQukYQ/default.jpg,True,True,False,The Hudson Union www.hudsonunionsociety.com is...,usa

In [33]:
full2 = full.drop(excluded.index)
print(f'lunghezza orginale database: {len(full)}')
print(f'excluded dataset {len(full) - len(full2)} righe')
print(f'lunghezza database full2 : {len(full2)}')
full2.head(2)

lunghezza orginale database: 375942
excluded dataset 2620 righe
lunghezza database full2 : 373322

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,usa
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John...",usa

In [34]:
## 5. Add a like_ratio column storing the ratio between the number of likes and of dislikes

In [35]:
def perc(row):
    if row['dislikes'] == 0:
        return None
    return row['likes'] / row['dislikes']

full2['like_ratio'] = full2.apply(perc, axis=1)
full2.head(2)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,usa,19.395482
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John...",usa,15.812724

In [36]:
## 6. Cluster the publish time into 10-minute intervals (e.g. from 02:20 to 02:30)

In [37]:
full2['publish_time'].dtype

dtype('O')

In [38]:
full2['publish_time'] = pd.to_datetime(full2['publish_time'])
full2.head(2)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13 17:13:01+00:00,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,usa,19.395482
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13 07:30:00+00:00,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John...",usa,15.812724

In [39]:
full2['hour'] = full2['publish_time'].dt.hour
full2['minutes'] = full2['publish_time'].dt.minute
full2.head(2)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,hour,minutes
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13 17:13:01+00:00,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,usa,19.395482,17,13
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13 07:30:00+00:00,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John...",usa,15.812724,7,30

In [40]:
full2['minutes_intervallo'] = full2['minutes']//10
full2.head(2)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,hour,minutes,minutes_intervallo
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13 17:13:01+00:00,SHANtell martin,748374,57527,2966,...,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,usa,19.395482,17,13,1
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13 07:30:00+00:00,"last week tonight trump presidency|""last week ...",2418783,97185,6146,...,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John...",usa,15.812724,7,30,3

In [41]:
## 7. For each interval, determine the number of videos, average number of likes and of dislikes.

In [42]:
full2.groupby(['hour','minutes_intervallo']).agg(
    conteggio=('video_id', 'count'),
    media_likes=('likes', 'mean'),
    media_dislikes=('dislikes', 'mean')
).round(2).head(3)

                         conteggio  media_likes  media_dislikes
hour minutes_intervallo
0    0                        2897     61288.12         3808.15
     1                        1509     22748.14         1449.84
     2                        1241     21378.28         1072.34

In [43]:
full2.groupby(['hour','minutes_intervallo'], as_index= False)[['likes', 'dislikes']].mean().head(3).round(2)

   hour  minutes_intervallo     likes  dislikes
0     0                   0  61288.12   3808.15
1     0                   1  22748.14   1449.84
2     0                   2  21378.28   1072.34

In [44]:
##8. For each tag, determine the number of videos. Notice that tags contains a string with several tags.

In [45]:
full2.head(2)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,hour,minutes,minutes_intervallo
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13 17:13:01+00:00,SHANtell martin,748374,57527,2966,...,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,usa,19.395482,17,13,1
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13 07:30:00+00:00,"last week tonight trump presidency|""last week ...",2418783,97185,6146,...,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John...",usa,15.812724,7,30,3

In [46]:
full2['tags'].str.count(r'\|').sort_values(ascending = False)

262064    151
287130    131
286953    131
286789    131
287531    131
         ...
14284       0
14279       0
308635      0
308631      0
308620      0
Name: tags, Length: 373322, dtype: int64

In [47]:
full2[full2['video_id'] == '1ZAPwfrtAFY']['tags']

1         last week tonight trump presidency|"last week ...
221       last week tonight trump presidency|"last week ...
454       last week tonight trump presidency|"last week ...
693       last week tonight trump presidency|"last week ...
930       last week tonight trump presidency|"last week ...
1158      last week tonight trump presidency|"last week ...
1374      last week tonight trump presidency|"last week ...
81832     last week tonight trump presidency|"last week ...
82037     last week tonight trump presidency|"last week ...
82274     last week tonight trump presidency|"last week ...
82593     last week tonight trump presidency|"last week ...
122692    last week tonight trump presidency"|"last week...
122966    last week tonight trump presidency"|"last week...
202329    last week tonight trump presidency|"last week ...
202557    last week tonight trump presidency|"last week ...
202811    last week tonight trump presidency|"last week ...
203086    last week tonight trump presidency|"last week ...
260335    last week tonight trump presidency|"last week ...
260532    last week tonight trump presidency|"last week ...
294781    last week tonight trump presidency|"last week ...
Name: tags, dtype: object

In [48]:
full2[full2['video_id'] == '1ZAPwfrtAFY']['tags'].unique()

array(['last week tonight trump presidency|"last week tonight donald trump"|"john oliver trump"|"donald trump"',
       'last week tonight trump presidency"|"last week tonight donald trump"|"john oliver trump"|"donald trump'],
      dtype=object)

In [49]:
full2['tags_lista'] = full2['tags'].str.replace('"', '', regex=False).str.split('|')

In [50]:
full2.head(2)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,hour,minutes,minutes_intervallo,tags_lista
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13 17:13:01+00:00,SHANtell martin,748374,57527,2966,...,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,usa,19.395482,17,13,1,[SHANtell martin]
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13 07:30:00+00:00,"last week tonight trump presidency|""last week ...",2418783,97185,6146,...,False,False,False,"One year after the presidential election, John...",usa,15.812724,7,30,3,"[last week tonight trump presidency, last week..."

In [51]:
tag_video = full2.explode('tags_lista', ignore_index = False)
print(tag_video.shape)
tag_video.head(6)

(6453816, 22)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,comments_disabled,ratings_disabled,video_error_or_removed,description,country,like_ratio,hour,minutes,minutes_intervallo,tags_lista
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13 17:13:01+00:00,SHANtell martin,748374,57527,2966,...,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,usa,19.395482,17,13,1,SHANtell martin
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13 07:30:00+00:00,"last week tonight trump presidency|""last week ...",2418783,97185,6146,...,False,False,False,"One year after the presidential election, John...",usa,15.812724,7,30,3,last week tonight trump presidency
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13 07:30:00+00:00,"last week tonight trump presidency|""last week ...",2418783,97185,6146,...,False,False,False,"One year after the presidential election, John...",usa,15.812724,7,30,3,last week tonight donald trump
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13 07:30:00+00:00,"last week tonight trump presidency|""last week ...",2418783,97185,6146,...,False,False,False,"One year after the presidential election, John...",usa,15.812724,7,30,3,john oliver trump
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13 07:30:00+00:00,"last week tonight trump presidency|""last week ...",2418783,97185,6146,...,False,False,False,"One year after the presidential election, John...",usa,15.812724,7,30,3,donald trump
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,...,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,usa,27.352126,19,5,0,racist superman

In [52]:
tag_video['tags_lista'].value_counts()

tags_lista
[none]                                  37209
funny                                   15039
comedy                                  12351
2018                                    11371
news                                     6363
                                        ...
тубус шоу                                   1
плохой сигнал                               1
декор в ванной комнате своими руками        1
room tour bathroom                          1
рум тур ванной комнаты                      1
Name: count, Length: 849303, dtype: int64

In [53]:
tag_video.groupby('tags_lista', as_index = False)['video_id'].nunique().sort_values('video_id', ascending=False)

                                               tags_lista  video_id
231721                                             [none]     23674
12818                                                2018      5750
355883                                              funny      4148
296169                                             comedy      3105
466732                                               news      3051
...                                                   ...       ...
849291  🔴 EA Konferenz Live! - Ab 19.30 - Die E3 start...         1
849292                      🔴 TE RETO A VERLO COMPLETO 🔴          1
849277  🔥 Страна ахнула! Путин ОБРАДОВАЛ пенсионеров.....         1
849278  🔥 Страна ахнула! Юлия Началова ОШЕЛОМИЛА заявл...         1
849279  🔥 Страна в ШОКЕ! Вот почему Басков КИНУЛ Лопыр...         1

[849303 rows x 2 columns]

In [54]:
## 9. Find the tags with the largest number of videos

In [55]:
tag_video.groupby('tags_lista')['video_id'].count().idxmax()

'[none]'

In [56]:
tag_video2 = tag_video[tag_video['tags_lista'] != '[none]']

In [57]:
tag_video2.groupby('tags_lista')['video_id'].count().idxmax()

'funny'

In [58]:
tag_video.groupby('tags_lista')['video_id'].count().sort_values(ascending = False).head(2)

tags_lista
[none]    37209
funny     15039
Name: video_id, dtype: int64

In [59]:
## 10. For each (tag, country) pair, compute average ratio likes/dislikes

In [60]:
tag_video.groupby(['tags_lista', 'country'])['like_ratio'].mean()

tags_lista                                       country
                                                 ca         13.400243
                                                 de         23.656067
                                                 fr         17.879422
                                                 in          8.137764
                                                 jp          9.894877
                                                              ...
😥                                                de         26.384615
😭 #résistancelamaindesqueezie ❤️                 fr         10.219048
😭قفز عسكري الوحيد من الطائرة العسكرية الجزائرية  fr          6.223873
🚀 smartpixel.com.ua                              ru          0.714286
🤝 ZARBEX zahlt Schutzgeld!!!                     de         13.989691
Name: like_ratio, Length: 1098660, dtype: float64

In [61]:
## 11. For each (trending_date, country) pair, the video with the largest number of views

In [62]:
videomax = full2.groupby(['trending_date', 'country'])['views'].idxmax()
videomax

trending_date  country
17.01.12       ca          44347
               de          85229
               fr         126201
               gb         166981
               in         205566
                           ...
18.31.05       jp         257741
               kr         292147
               mx         332432
               ru         373007
               usa         38146
Name: views, Length: 1967, dtype: int64

In [63]:
names = full2.loc[videomax, ['trending_date', 'country','title']]
names

,trending_date,country,title
44347,17.01.12,ca,Marvel Studios' Avengers: Infinity War Officia...
85229,17.01.12,de,Marvel Studios' Avengers: Infinity War Officia...
126201,17.01.12,fr,Avengers: Infinity War Trailer Tease
166981,17.01.12,gb,"Luis Fonsi, Demi Lovato - Échame La Culpa"
205566,17.01.12,in,Marvel Studios' Avengers: Infinity War Officia...
...,...,...,...
257741,18.31.05,jp,Maroon 5 - Girls Like You ft. Cardi B
292147,18.31.05,kr,[MV] AOA _ Bingle Bangle(빙글뱅글)
332432,18.31.05,mx,"Cardi B, Bad Bunny & J Balvin - I Like It [Off..."
373007,18.31.05,ru,[BadComedian] - Движение Вверх (Плагиат или ве...
38146,18.31.05,usa,Childish Gambino - This Is America (Official V...

In [64]:
## 12. Divide trending_date into three columns: year, month, day

In [65]:
full2['trending_date'].dtype

dtype('O')

In [66]:
full2['trending_date'].str.match(r'^\d{2}\.\d{2}\.\d{2}$').value_counts()

trending_date
True    373322
Name: count, dtype: int64

In [67]:
full2[['tr_year', 'tr_day', 'tr_month']] = full2['trending_date'].str.split('.', expand= True)
full2.head(1)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,...,description,country,like_ratio,hour,minutes,minutes_intervallo,tags_lista,tr_year,tr_day,tr_month
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13 17:13:01+00:00,SHANtell martin,748374,57527,2966,...,SHANTELL'S CHANNEL - https://www.youtube.com/s...,usa,19.395482,17,13,1,[SHANtell martin],17,14,11

In [68]:
## 13. For each (month, country) pair, the video with the largest number of views

In [69]:
indici = full2.groupby(['tr_month', 'country'])['views'].idxmax()
video_month = full2.loc[indici, ['tr_month', 'country','title']]
video_month

       tr_month country                                              title
52163        01      ca  Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...
92879        01      de  Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...
133802       01      fr  Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...
176157       01      gb  Bruno Mars - Finesse (Remix) [Feat. Cardi B] [...
214354       01      in     Taylor Swift - End Game ft. Ed Sheeran, Future
...         ...     ...                                                ...
207718       12      in  YouTube Rewind: The Shape of 2017 | #YouTubeRe...
265041       12      kr  YouTube Rewind: The Shape of 2017 | #YouTubeRe...
300013       12      mx  YouTube Rewind: The Shape of 2017 | #YouTubeRe...
340036       12      ru  YouTube Rewind: The Shape of 2017 | #YouTubeRe...
6181         12     usa  YouTube Rewind: The Shape of 2017 | #YouTubeRe...

[77 rows x 3 columns]

In [70]:
## 14. Read all json files with the video categories

In [71]:
category_files = {
    'usa': 'US',
    'ca':  'CA',
    'de':  'DE',
    'fr':  'FR',
    'gb':  'GB',
    'in':  'IN',
    'jp':  'JP',
    'kr':  'KR',
    'mx':  'MX',
    'ru':  'RU',
}

categorie = {}
for country, code in category_files.items():
    categorie[country] = pd.read_json(os.path.join(os.getcwd(), 'YT file', f'{code}_category_id.json'))

In [72]:
for c in categorie:
    print(c, categorie[c].shape)

usa (32, 3)
ca (31, 3)
de (31, 3)
fr (31, 3)
gb (31, 3)
in (31, 3)
jp (31, 3)
kr (31, 3)
mx (31, 3)
ru (31, 3)

In [73]:
categorie['usa']

,kind,etag,items
0,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
1,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
2,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
3,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
4,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
5,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
6,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
7,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
8,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
9,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
10,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
11,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
12,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
13,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
14,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
15,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
16,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
17,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
18,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
19,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
20,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
21,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
22,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
23,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
24,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
25,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
26,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
27,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
28,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
29,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
30,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
31,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."

In [74]:
categorie['usa']['kind'][0]

'youtube#videoCategoryListResponse'

In [75]:
categorie['usa']['etag'][0]

'"m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJvJAAShlR6hM"'

In [76]:
categorie['usa']['items'][0]

{'kind': 'youtube#videoCategory',
 'etag': '"m2yskBQFythfE4irbTIeOgYYfBU/Xy1mB4_yLrHy_BmKmPBggty2mZQ"',
 'id': '1',
 'snippet': {'channelId': 'UCBR8-60-B28hp2BmDPdntcQ',
  'title': 'Film & Animation',
  'assignable': True}}

In [77]:
## 15. For each country, determine how many videos have a category that is not assignable.

In [78]:
non_assegnabili = {}

for country, df in categorie.items():
    lista_id = []
    for i in df['items']:
        if i['snippet']['assignable'] == False:
            lista_id.append(int(i['id']))
    non_assegnabili[country] = lista_id

In [79]:
non_assegnabili

{'usa': [18, 21, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
 'ca': [18, 21, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
 'de': [18, 21, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
 'fr': [18, 21, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
 'gb': [18, 21, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
 'in': [18, 21, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
 'jp': [18, 21, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
 'kr': [18, 21, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
 'mx': [18, 21, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
 'ru': [18, 21, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]}

In [80]:
ids = non_assegnabili['usa']
ids

[18, 21, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]

In [81]:
full3 = full2[full2['category_id'].isin(ids)]
print(full3.groupby('country').size())

country
ca     130
de     110
fr     112
gb      20
in     221
kr     167
mx       3
ru     195
usa     57
dtype: int64